import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import archiver from "archiver";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TEMPLATES_DIR = path.join(__dirname, "..", "portfolio-templates", "base");
const VALID_THEMES = ["minimal", "dark-glass"];

/**
 * Generate a portfolio ZIP from resume data and a chosen theme.
 * Returns a readable stream of the ZIP archive.
 */
export function generatePortfolioZip(resumeData, theme, res) {
  if (!VALID_THEMES.includes(theme)) {
    throw new Error(
      `Invalid theme "${theme}". Choose from: ${VALID_THEMES.join(", ")}`,
    );
  }

  // Prepare the resume data for injection
  const cleanData = {
    full_name: resumeData.full_name,
    email: resumeData.email,
    phone: resumeData.phone,
    linkedin: resumeData.linkedin,
    github: resumeData.github,
    summary: resumeData.summary,
    education: resumeData.education?.map((edu) => ({
      institution: edu.institution,
      location: edu.location,
      degree: edu.degree,
      start_date: edu.start_date,
      end_date: edu.end_date,
    })),
    projects: resumeData.projects?.map((project) => ({
      title: project.title,
      tech_stack: project.tech_stack,
      duration: project.duration,
      description: project.description,
      points: project.points?.map((p) => (typeof p === "string" ? p : p.point)),
    })),
    skills: resumeData.skills?.map((skill) => ({
      category: skill.category,
      items: skill.items,
    })),
    experiences: resumeData.experiences?.map((exp) => ({
      role: exp.role,
      company: exp.company,
      location: exp.location,
      start_date: exp.start_date,
      end_date: exp.end_date,
      points: exp.points?.map((p) => (typeof p === "string" ? p : p.point)),
    })),
  };

  const dataFileContent = `// This file is auto-generated by ResumeGen\nconst resumeData = ${JSON.stringify(cleanData, null, 2)};\n\nexport default resumeData;\n`;

  // Read App.jsx template and inject theme
  const appJsxPath = path.join(TEMPLATES_DIR, "src", "App.jsx");
  const appJsxContent = fs
    .readFileSync(appJsxPath, "utf-8")
    .replaceAll("{{THEME}}", theme);

  // Create ZIP archive
  const archive = archiver("zip", { zlib: { level: 9 } });

  archive.on("error", (err) => {
    throw err;
  });

  // Pipe the archive to the response
  archive.pipe(res);

  // Add all template files, replacing data.js and App.jsx with injected versions
  addDirectoryToArchive(archive, TEMPLATES_DIR, "portfolio", {
    "src/data.js": dataFileContent,
    "src/App.jsx": appJsxContent,
  });

  archive.finalize();
}

/**
 * Recursively add a directory to the archive, with optional file overrides.
 */
function addDirectoryToArchive(archive, dirPath, archivePrefix, overrides) {
  const entries = fs.readdirSync(dirPath, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry.name);
    const archivePath = path.join(archivePrefix, entry.name);
    // Normalize path separators for ZIP
    const normalizedArchivePath = archivePath.replace(/\\/g, "/");

    if (entry.isDirectory()) {
      addDirectoryToArchive(archive, fullPath, archivePath, overrides);
    } else {
      // Calculate relative path from TEMPLATES_DIR
      const relativePath = path
        .relative(TEMPLATES_DIR, fullPath)
        .replace(/\\/g, "/");

      if (overrides[relativePath]) {
        // Use the overridden content
        archive.append(overrides[relativePath], {
          name: normalizedArchivePath,
        });
      } else {
        // Use original file
        archive.file(fullPath, { name: normalizedArchivePath });
      }
    }
  }
}
